// 센서 위치 및 더미 데이터 상수 분리
export const GAS_SENSORS = [
  { id: 'gas-1', x: 128, y: 80, name: '가스감지기1' },
  { id: 'gas-2', x: 263, y: 88, name: '가스감지기2' },
  { id: 'gas-3', x: 333, y: 88, name: '가스감지기3' },
  { id: 'gas-4', x: 263, y: 253, name: '가스감지기4' },
  { id: 'gas-5', x: 333, y: 253, name: '가스감지기5' },
  { id: 'gas-6', x: 448, y: 253, name: '가스감지기6' },
  { id: 'gas-7', x: 448, y: 88, name: '가스감지기7' },
  { id: 'gas-8', x: 522, y: 93, name: '가스감지기8' },
  { id: 'gas-9', x: 522, y: 233, name: '가스감지기9' },
  { id: 'gas-10', x: 559, y: 108, name: '가스감지기10' },
  { id: 'gas-11', x: 559, y: 220, name: '가스감지기11' },
  { id: 'gas-12', x: 612, y: 163, name: '가스감지기12' },
  { id: 'gas-13', x: 662, y: 163, name: '가스감지기13' },
  { id: 'gas-14', x: 328, y: 334, name: '가스감지기14' },
  { id: 'gas-15', x: 458, y: 334, name: '가스감지기15' },
];

export const FIRE_SENSORS = [
  { id: 'fire-1', x: 210, y: 263, name: '화재감지기1' },
  { id: 'fire-2', x: 210, y: 375, name: '화재감지기2' },
  { id: 'fire-3', x: 485, y: 263, name: '화재감지기3' },
  { id: 'fire-4', x: 575, y: 249, name: '화재감지기4' },
  { id: 'fire-5', x: 485, y: 76, name: '화재감지기5' },
  { id: 'fire-6', x: 602, y: 76, name: '화재감지기6' },
];

export const VIBRATION_SENSORS = [
  { id: 'vibration-1', x: 260, y: 313, name: '진동감지기1' },
  { id: 'vibration-2', x: 277, y: 365, name: '진동감지기2' },
  { id: 'vibration-3', x: 295, y: 313, name: '진동감지기3' },
  { id: 'vibration-4', x: 390, y: 313, name: '진동감지기4' },
  { id: 'vibration-5', x: 407, y: 365, name: '진동감지기5' },
  { id: 'vibration-6', x: 427, y: 313, name: '진동감지기6' },
  { id: 'vibration-7', x: 523, y: 118, name: '진동감지기7' },
  { id: 'vibration-8', x: 523, y: 193, name: '진동감지기8' },
  { id: 'vibration-9', x: 559, y: 133, name: '진동감지기9' },
];

export const FACILITY_DETAIL = {
  name: '삼척 교동 수소 스테이션',
  type: '대체연료충전소',
  address: '강원특별자치도 삼척시 교동 산 209',
  status: 'open',
  phone: '033-575-5189 ext. 90',
  imageUrl: '/images/monitoring/facility1.jpg',
  operationHours: '09:00 ~ 18:00',
  capacity: '250kg/일',
  pressure: '700bar',
  sensors: {
    gas: [
      { id: 1, name: '가스감지기1', unit: '--', status: 'normal' },
      { id: 2, name: '가스감지기2', unit: '--', status: 'normal' },
      { id: 3, name: '가스감지기3', unit: '--', status: 'normal' },
      { id: 4, name: '가스감지기4', unit: '--', status: 'normal' },
      { id: 5, name: '가스감지기5', unit: '--', status: 'normal' },
      { id: 6, name: '가스감지기6', unit: '--', status: 'normal' },
      { id: 7, name: '가스감지기7', unit: '--', status: 'normal' },
      { id: 8, name: '가스감지기8', unit: '--', status: 'normal' },
      { id: 9, name: '가스감지기9', unit: '--', status: 'normal' },
      { id: 10, name: '가스감지기10', unit: '--', status: 'normal' },
      { id: 11, name: '가스감지기11', unit: '--', status: 'normal' },
      { id: 12, name: '가스감지기12', unit: '--', status: 'normal' },
      { id: 13, name: '가스감지기13', unit: '--', status: 'normal' },
      { id: 14, name: '가스감지기14', unit: '--', status: 'normal' },
      { id: 15, name: '가스감지기15', unit: '--', status: 'normal' },
    ],
    fire: [
      { id: 16, name: '화재감지기1', unit: '--', status: 'normal' },
      { id: 17, name: '화재감지기2', unit: '--', status: 'normal' },
      { id: 18, name: '화재감지기3', unit: '--', status: 'normal' },
      { id: 19, name: '화재감지기4', unit: '--', status: 'normal' },
      { id: 20, name: '화재감지기5', unit: '--', status: 'normal' },
      { id: 21, name: '화재감지기6', unit: '--', status: 'normal' },
    ],
    vibration: [
      {
        id: 22,
        name: '진동감지기1',
        value: '0.85',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 23,
        name: '진동감지기2',
        value: '0.92',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 24,
        name: '진동감지기3',
        value: '0.78',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 25,
        name: '진동감지기4',
        value: '0.88',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 26,
        name: '진동감지기5',
        value: '0.95',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 27,
        name: '진동감지기6',
        value: '0.82',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 28,
        name: '진동감지기7',
        value: '0.87',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 29,
        name: '진동감지기8',
        value: '0.91',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
      {
        id: 30,
        name: '진동감지기9',
        value: '0.84',
        unit: 'g',
        status: 'normal',
        data: [],
        detailedData: [],
      },
    ],
  },
};
